jaffle_shop:
  target: dev
  outputs:
    dev:
      type: databricks
      schema: default
      host: dbc-2aec941b-f559.cloud.databricks.com
      http_path: /sql/1.0/warehouses/6bb1bada6e82ee18
      token: "{{ env_var('DATABRICKS_TOKEN') | as_text }}"
