jaffle_shop:
  outputs:
    default:
      type: snowflake
      account: ls44702.eu-central-1
      warehouse: COMPUTE_WH
      database: airbnb
      role: transform
      user: montara
      password: {{ env_var('SNOWFLAKE_PASSWORD') }}
      schema: test_e5jj6ggu_ezztt_com
      threads: 4
