jaffle_shop:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: 127.0.0.1
      port: 5432
      user: admin
      password: admin
      dbname: postgres
      schema: exercise
      threads: 32
