version: 2

models:
  - name: constraints_snapshot_example
    docs:
      node_color: black
    config:
      constraints_enabled: true
    columns:
      - name: test
        data_type: integer
        description: hello
        constraints: 
          - not null
          - primary key
        check: (id > 0)
        tests:
          - unique
      - name: color
        data_type: text
      - name: date_day
        data_type: date