jaffle_shop:
  outputs:
    dev:
      account: ls44702.eu-central-1
      database: airbnb
      password: BAD_PASSWORD
      role: transform
      schema: test_e5jj6ggu_ezztt_com
      threads: 2
      type: snowflake
      user: montara
      warehouse: COMPUTE_WH
    prod:
      account: ls44702.eu-central-1
      database: airbnb
      password: BHW9yze.vyb_nwz.xnp
      role: transform
      schema: prod_e5jj6ggu_ezztt_com
      threads: 4
      type: snowflake
      user: montara
      warehouse: COMPUTE_WH
