name: build github actions
on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11.1"
      - run: pip install -r requirements.txt
      - run: mnt
