version: 2

sources:
  - name: jaffle_shop
    description: a demo source for jaffle shop
    schema: KOS_DBT_TEST_MANUAL
    meta:
      favorite_color: red
    tables:
      - name: stg_orders
        meta:
          is_source_table: true
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
            meta:
              column_note: "column meta test value"
